#! /bin/sh
### BEGIN INIT INFO
# Provides:          lcdd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LCD daemon
# Description:       Monitors a pipe and sends inputs to LCD
### END INIT INFO

case "$1" in
  start)
      echo "Starting LCD daemon"
      mkfifo  /dev/lcd > /dev/null 2>&1
      /usr/local/sbin/LCDd.py &
      echo "$!" > /var/run/lcdd.pid
      echo "running..." > /dev/lcd
      ;;
   stop)
      echo "Stopping LCD daemon"
      echo " STOPPED " > /dev/lcd
      sleep 2
      kill $(cat /var/run/lcdd.pid)
      rm -f /var/run/lcdd.pid
      rm /dev/lcd > /dev/null 2>&1
      ;;
      *)
      echo "Usage: /etc/init.d/lcdd {start|stop}"
      exit 1
      ;;
esac

exit 0
